<section>
    <form>

        <div class="form-input">
            <label>Name</label>
            <input type="text" placeholder="Name" name="name" required>
        </div>

        <div class="form-input">
            <label>Code</label>
            <input type="text" placeholder="Code" name="code" required>
        </div>

        <div class="form-input">
            <label>Dni</label>
            <input type="text" placeholder="Dni" name="dni" required>
        </div>

        <button type="submit" class="">Enviar</button>
    </form>
</section>



